[toolchain]
channel = "nightly-2025-06-22"
# components = [ "llvm-tools-preview" ]
# components = ["rust-analyzer", "clippy"]
targets = ["x86_64-unknown-linux-gnu", "x86_64-pc-windows-gnu", "x86_64-pc-windows-msvc", "aarch64-unknown-linux-gnu" ]
# targets = ["riscv32imc-unknown-none-elf" ]
profile = "default"
